version: '3.9'
services:
  mssql:
    image: mcr.microsoft.com/mssql/server:latest

  redis:
    image: redis
        
  catalog-api:
    image: shop/catalog-api
    build: 
      context: .
      dockerfile: Services\Catalog\Catalog.Api\Dockerfile
    depends_on:
      - mssql
      - rabbitmq

  basket-api:
    image: shop/basket-api
    build: 
      context: .
      dockerfile: Services\Basket\Basket.Api\Dockerfile
    depends_on:
      - redis
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management-alpine

